name: Refke
main: com.gmail.gamebot1080.Refke.Refke
version: 1.0
description: for the moment this only say the name of refs
commands:
  ref:
    description: for the moment this only say the name of refs.
    
